server:
  port: 8763
  context-path: /message
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
#  mail:
#    host: smtp.163.com
#    username: yushengjun2018@163.com
#    password: itmayiedu644
#    enable:  true
#    smtp:
#      auth: true
#    starttls:
#      enable: true
#      required: true
  mail:
    host: smtp.163.com
    username: 18768866992@163.com
    password: BRHYMCVEVKEDSOLN
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
   # port: 465
    default-encoding: utf-8
########################################

msg: 
  subject: IT实验室|温馨提示您，会员注册成功邮件。
  text: 您好，恭喜您的账户{},注册成功!IT实验室|教育 渡风的IT实验室 www.baidu.com
